/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOn { 'dailyCostUSD' : number, 'name' : string }
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'thumbnailUrl' : [] | [string],
  'date' : bigint,
  'published' : boolean,
  'author' : string,
}
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'paymentMethod' : { 'stripe' : null },
  'endDate' : bigint,
  'carId' : bigint,
  'user' : Principal,
  'totalAmountUSD' : number,
  'addOns' : Array<AddOn>,
  'startDate' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Car {
  'id' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'isActive' : boolean,
  'availability' : boolean,
  'dailyRateUSD' : number,
  'transmission' : TransmissionType,
  'category' : CarCategory,
}
export type CarCategory = { 'suv' : null } |
  { 'van' : null } |
  { 'economy' : null } |
  { 'luxury' : null };
export interface DiscountCode {
  'code' : string,
  'isActive' : boolean,
  'expiry' : bigint,
  'percentage' : bigint,
}
export interface Review {
  'carId' : bigint,
  'user' : Principal,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type TransmissionType = { 'automatic' : null } |
  { 'manual' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookCar' : ActorMethod<[bigint, bigint, bigint, Array<AddOn>], Booking>,
  /**
   * / Users can cancel their own bookings that are still pending or confirmed.
   */
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createCar' : ActorMethod<
    [string, CarCategory, TransmissionType, number, Array<string>],
    Car
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Admin-only: create or update a blog post.
   */
  'createOrUpdateBlogPost' : ActorMethod<
    [string, string, string, boolean, [] | [string], [] | [bigint]],
    BlogPost
  >,
  /**
   * / Admin-only: create a promo code.
   */
  'createPromoCode' : ActorMethod<[string, bigint, bigint], DiscountCode>,
  /**
   * / Admin-only: deactivate a promo code.
   */
  'deactivatePromoCode' : ActorMethod<[string], undefined>,
  'deleteCar' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only: get all blog posts including unpublished ones.
   */
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  /**
   * / Admin-only: view all bookings, optionally filtered by status.
   */
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  /**
   * / Admin-only: get all registered user principals with their booking counts.
   */
  'getAllUsers' : ActorMethod<[], Array<[Principal, bigint]>>,
  /**
   * / Anyone can browse available cars — no auth required.
   */
  'getAvailableCars' : ActorMethod<[], Array<Car>>,
  /**
   * / Anyone can read a single published blog post — no auth required.
   */
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  /**
   * / Admin-only: view bookings filtered by status.
   */
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Anyone can view a single car's details — no auth required.
   */
  'getCar' : ActorMethod<[bigint], [] | [Car]>,
  /**
   * / Anyone can read reviews for a car — no auth required.
   */
  'getCarReviews' : ActorMethod<[bigint], Array<Review>>,
  /**
   * / Users can only see their own bookings; admins can see all bookings.
   */
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  /**
   * / Anyone can read published blog posts — no auth required.
   */
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  /**
   * / Admin-only: get per-car revenue breakdown from completed bookings.
   */
  'getRevenuePerCar' : ActorMethod<[], Array<[bigint, number]>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Admin-only: get total revenue from completed bookings.
   */
  'getTotalRevenue' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Admin-only: change booking status (confirm, complete, cancel).
   */
  'setBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleCarAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCar' : ActorMethod<
    [
      bigint,
      string,
      CarCategory,
      TransmissionType,
      number,
      Array<string>,
      boolean,
      boolean,
    ],
    Car
  >,
  /**
   * / Authenticated users can validate a promo code before applying it.
   */
  'validatePromoCode' : ActorMethod<[string], [] | [DiscountCode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];