/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AddOn = IDL.Record({
  'dailyCostUSD' : IDL.Float64,
  'name' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'paymentMethod' : IDL.Variant({ 'stripe' : IDL.Null }),
  'endDate' : IDL.Int,
  'carId' : IDL.Nat,
  'user' : IDL.Principal,
  'totalAmountUSD' : IDL.Float64,
  'addOns' : IDL.Vec(AddOn),
  'startDate' : IDL.Int,
});
export const CarCategory = IDL.Variant({
  'suv' : IDL.Null,
  'van' : IDL.Null,
  'economy' : IDL.Null,
  'luxury' : IDL.Null,
});
export const TransmissionType = IDL.Variant({
  'automatic' : IDL.Null,
  'manual' : IDL.Null,
});
export const Car = IDL.Record({
  'id' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'availability' : IDL.Bool,
  'dailyRateUSD' : IDL.Float64,
  'transmission' : TransmissionType,
  'category' : CarCategory,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'date' : IDL.Int,
  'published' : IDL.Bool,
  'author' : IDL.Text,
});
export const DiscountCode = IDL.Record({
  'code' : IDL.Text,
  'isActive' : IDL.Bool,
  'expiry' : IDL.Int,
  'percentage' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'carId' : IDL.Nat,
  'user' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookCar' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Int, IDL.Vec(AddOn)],
      [Booking],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createCar' : IDL.Func(
      [IDL.Text, CarCategory, TransmissionType, IDL.Float64, IDL.Vec(IDL.Text)],
      [Car],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [BlogPost],
      [],
    ),
  'createPromoCode' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Int],
      [DiscountCode],
      [],
    ),
  'deactivatePromoCode' : IDL.Func([IDL.Text], [], []),
  'deleteCar' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getAvailableCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCar' : IDL.Func([IDL.Nat], [IDL.Opt(Car)], ['query']),
  'getCarReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getRevenuePerCar' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalRevenue' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleCarAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCar' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        CarCategory,
        TransmissionType,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
      ],
      [Car],
      [],
    ),
  'validatePromoCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DiscountCode)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AddOn = IDL.Record({ 'dailyCostUSD' : IDL.Float64, 'name' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'paymentMethod' : IDL.Variant({ 'stripe' : IDL.Null }),
    'endDate' : IDL.Int,
    'carId' : IDL.Nat,
    'user' : IDL.Principal,
    'totalAmountUSD' : IDL.Float64,
    'addOns' : IDL.Vec(AddOn),
    'startDate' : IDL.Int,
  });
  const CarCategory = IDL.Variant({
    'suv' : IDL.Null,
    'van' : IDL.Null,
    'economy' : IDL.Null,
    'luxury' : IDL.Null,
  });
  const TransmissionType = IDL.Variant({
    'automatic' : IDL.Null,
    'manual' : IDL.Null,
  });
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'availability' : IDL.Bool,
    'dailyRateUSD' : IDL.Float64,
    'transmission' : TransmissionType,
    'category' : CarCategory,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'date' : IDL.Int,
    'published' : IDL.Bool,
    'author' : IDL.Text,
  });
  const DiscountCode = IDL.Record({
    'code' : IDL.Text,
    'isActive' : IDL.Bool,
    'expiry' : IDL.Int,
    'percentage' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'carId' : IDL.Nat,
    'user' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookCar' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Int, IDL.Vec(AddOn)],
        [Booking],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createCar' : IDL.Func(
        [
          IDL.Text,
          CarCategory,
          TransmissionType,
          IDL.Float64,
          IDL.Vec(IDL.Text),
        ],
        [Car],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [BlogPost],
        [],
      ),
    'createPromoCode' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Int],
        [DiscountCode],
        [],
      ),
    'deactivatePromoCode' : IDL.Func([IDL.Text], [], []),
    'deleteCar' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getAvailableCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCar' : IDL.Func([IDL.Nat], [IDL.Opt(Car)], ['query']),
    'getCarReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getRevenuePerCar' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalRevenue' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleCarAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCar' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          CarCategory,
          TransmissionType,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
        ],
        [Car],
        [],
      ),
    'validatePromoCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DiscountCode)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };